<?php
/**
 * LogListResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalSystem
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal System API documentation
 *
 * Bumbal System API documentation for System Management Calls
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalSystem;

/**
 * LogListResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description LogListResponse
/**
 * @package     BumbalSystem
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LogListResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LogListResponse"
     */
    public function testLogListResponse()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "count_filtered"
     */
    public function testPropertyCountFiltered()
    {
    }

    /**
     * Test attribute "count_unfiltered"
     */
    public function testPropertyCountUnfiltered()
    {
    }

    /**
     * Test attribute "count_limited"
     */
    public function testPropertyCountLimited()
    {
    }
}
