<?php
/**
 * KeyringApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalSystem
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal System API documentation
 *
 * Bumbal System API documentation for System Management Calls
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalSystem;

use \BumbalSystem\Configuration;
use \BumbalSystem\ApiClient;
use \BumbalSystem\ApiException;
use \BumbalSystem\ObjectSerializer;

/**
 * KeyringApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalSystem
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KeyringApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for removeKey
     *
     * Remove a key from the key ring.
     *
     */
    public function testRemoveKey()
    {
    }

    /**
     * Test case for retrieveKeyRing
     *
     * Retrieve KeyRing.
     *
     */
    public function testRetrieveKeyRing()
    {
    }

    /**
     * Test case for setKey
     *
     * Set a key to the key ring.
     *
     */
    public function testSetKey()
    {
    }
}
